services:
  backend:
    build:
      context: .
      dockerfile: ./backend/DockerFile
    env_file:
      - .env
    container_name: talent_navigator_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./backend:/app/backend
      - ./frontend:/app/frontend 
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_healthy
    networks:
      - app-network

  frontend:
    build:
      context: .
      dockerfile: ./frontend/DockerFile
    container_name: talent_navigator_frontend
    command: streamlit run app.py --server.port 8501 --server.address 0.0.0.0
    volumes:
      - ./frontend:/app
    ports:
      - "8501:8501"
    depends_on:
      - backend
    networks:
      - app-network

  redis:
    image: "redis:7-alpine"
    container_name: talent_navigator_redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
      - ./redis-config/redis.conf:/usr/local/etc/redis/redis.conf
    command: redis-server /usr/local/etc/redis/redis.conf
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  db-loader:
    build:
      context: .
      dockerfile: ./backend/DockerFile
    container_name: talent_navigator_db_loader

    command: python load_redis_from_json.py
    volumes:
      - ./:/app
    networks:
      - app-network
    depends_on:
      redis:
        condition: service_healthy
    profiles:
      - load_db


networks:
  app-network:
    driver: bridge

volumes:
  redis-data:
    driver: local